# Banco de dados
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT / OAuth2 Resource Server
app.jwt.private-key=${JWT_PRIVATE_KEY}
app.jwt.public-key=${JWT_PUBLIC_KEY}
app.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS}

# Configurações gerais
spring.application.name=parusya
server.port=${PORT}

# Evita falhas de AWT em ambientes sem display (Railway, Docker)
java.awt.headless=true
